<?xml version="1.0"?>

<!--
Skin configuration file. This file contains details of your project, which will
be used to configure the chosen Forrest skin.

jefft@apache.org
-->

<!DOCTYPE skinconfig [

  <!ENTITY % links.att 'name CDATA #REQUIRED'>
  <!ENTITY % link.att 'name CDATA #REQUIRED href CDATA #REQUIRED'>
  <!ELEMENT skinconfig (disable-search?, searchsite-domain?, searchsite-name?,
  project-name, project-url, project-logo, group-name?, group-url?, group-logo?,
  host-url?, host-logo?, year?, vendor?, trail?, credits?)*>
  <!ELEMENT credits (credit*)>
  <!ELEMENT credit (name, url, image?, width?, height?)>
  <!-- id uniquely identifies the tool, and role indicates its function -->
  <!ATTLIST credit id   CDATA #IMPLIED
                   role CDATA #IMPLIED>
  <!ELEMENT disable-search (#PCDATA)>
  <!ELEMENT searchsite-domain (#PCDATA)>
  <!ELEMENT searchsite-name (#PCDATA)>
  <!ELEMENT project-name (#PCDATA)>
  <!ELEMENT project-url (#PCDATA)>
  <!ELEMENT project-logo (#PCDATA)>
  <!ELEMENT group-name (#PCDATA)>
  <!ELEMENT group-url (#PCDATA)>
  <!ELEMENT group-logo (#PCDATA)>
  <!ELEMENT host-url (#PCDATA)>
  <!ELEMENT host-logo (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT vendor (#PCDATA)>
  <!ELEMENT trail (link1, link2, link3)>
  <!ELEMENT link1 EMPTY>
  <!-- Seems we can't use param entity refs until this is DTDified -->
  <!ATTLIST link1 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT link2 EMPTY>
  <!ATTLIST link2 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT link3 EMPTY>
  <!ATTLIST link3 name CDATA #REQUIRED href CDATA #IMPLIED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT image (#PCDATA)>
  <!ELEMENT width (#PCDATA)>
  <!ELEMENT height (#PCDATA)>
  ]>

<skinconfig>
  <!-- Do we want the Google search box? -->
  <disable-search>false</disable-search>
  <searchsite-domain>xml.apache.org</searchsite-domain>
  <searchsite-name>Apache XML</searchsite-name>


  <project-name>FOP</project-name>
  <project-url>http://xml.apache.org/fop/</project-url>
  <project-logo>images/logo.jpg</project-logo>

  <group-name>Apache XML</group-name>
  <group-url>http://xml.apache.org/</group-url>
  <group-logo>images/group-logo.gif</group-logo>

  <!-- Eg, a sourceforge logo. forrest-site renders it to the bottom-left corner -->
  <host-logo></host-logo>

  <!-- The following used to construct a copyright statement -->
  <year>1999-2003</year>
  <vendor>The Apache Software Foundation.</vendor>

  <!-- Some skins use this to form a 'breadcrumb trail' of links. If you don't
  want these, set the attributes to blank. The DTD purposefully requires them.
  -->
  <trail>
    <link1 name="apache" href="http://www.apache.org/"/>
    <link2 name="xml.apache" href="http://xml.apache.org/"/>
    <link3 name="" href=""/>
  </trail>

  <!-- Credits are typically rendered as a set of small clickable images in the
  page footer -->
  <credits>
    <!--<credit>
      <name>Built with Cocoon</name>
      <url>http://xml.apache.org/cocoon/</url>
      <image>skin/images/built-with-cocoon.gif</image>
      <width>88</width>
      <height>31</height>
    </credit>
    <credit>
      <name>Krysalis Centipede</name>
      <url>http://www.krysalis.org/centipede/</url>
      <image>skin/images/centipede-logo-small.gif</image>
      <width>138</width>
      <height>31</height>
    </credit>-->
    <credit role="pdf">
      <name>Created by: FOP 1.0dev</name>
      <url>http://xml.apache.org/fop/dev</url>
      <image>images/logo.jpg</image>
      <width>138</width>
      <height>31</height>
    </credit>
  </credits>
</skinconfig>
